#pragma once
#include "trivia.h"

numstrs_t numstrs = {
{ 670616629, "Speed of light in miles per hour" },
{ 250000000, "Total population of America" },
{ 30000000, "Population of england in 1901" },
{ 10000000, "The number of Dark Side of the moon copies sold" },
{ 8900000, "Estimated population of england at time of first census" },
{ 4500000, "The population of Norway" },
{ 3750000, "Population of england at the time of the black death" },
{ 2000000, "Number of uk buildings that have broadband" },
{ 1100000, "Population of england at the time of the norman invasion" },
{ 1000000, "Dr. Evil's preferred ransom in dollars" },
{ 1500000, "Number of companies listed in 'euro pages'" },
{ 312000, "Weight of the Statue of Liberty in pounds" },
{ 280181, "Number of post offices in India" },
{ 250000, "Number of deaths per year from the flu" },
{ 187888, "Number of lakes in Finland" },
{ 151485, "Length of the Canadian coastline in feet" },
{ 138435, "Length of a marathon in feet" },
{ 125000, "The price paid by the Yankees for Babe Ruth" },
{ 107501, "Seating capacity at Michigan Stadium" },
{ 90854, "Weight of the Washington Monument in tons" },
{ 68894, "Number of cast in Around the World in 80 days" },
{ 63360, "Number of inches in a mile" },
{ 58220, "Number of names inscribed on the Vietnam Memorial" },
{ 57285, "Maximum fuel capacity of a Boeing 747 in gallons" },
{ 52455, "Number of islands in Canada" },
{ 51201, "Population of Twin Peaks" },
{ 46656, "Number of cubic inches in one cubic yard" },
{ 43306, "Weight of the Gateway Arch in tons" },
{ 40000, "AD Setting of the film barbarella" },
{ 38387, "Total points scored by Kareem Abdul-Jabbar" },
{ 36000, "Typical quantity of gills on a porcupine" },
{ 30000, "Size of the barclay families ranch in acres in \"the big valley\"" },
{ 28000, "Size of the Mississipi plantation in cat in a hot tin roof in acres" },
{ 15140, "Amount of money included in Monopoly in dollars" },
{ 13677, "Number of islands in Indonesia" },
{ 10000, "Years that the genie was in the lamp before Aladdin let him out" },
{ 68829, "Consecutive games won by the Harlem Globetrotters" },
{ 8430, "Maximum range of a Boeing 747 in miles" },
{ 7485, "Number of Cats performances on Broadway before closing" },
{ 6400, "Fahrenheit melting point of carbon" },
{ 6009, "Next calender year that will read the same upside down" },
{ 6000, "Number of questions included in an edition of trivial persuit" },
{ 5280, "Number of feet to one mile" },
{ 5005, "Number of rooms at the MGM Grand in Las Vegas" },
{ 5000, "The maximum prize money you could win on Win Ben Stein's Money" },
{ 4840, "Number of square years to one acre" },
{ 4350, "Cost of a first class suite on Titanic in dollars" },
{ 4049, "Number of line in John Keat's Endymion" },
{ 3955, "Setting of the Planet of the Apes movies, A.D." },
{ 3933, "Number of lines in Hamlet" },
{ 3562, "Number of MLB games played by Pete Rose" },
{ 3108, "Area of Juneau, Alaska in sqaure miles" },
{ 3000, "Length of an Olympic steeplechase" },
{ 2930, "Number of different people mentioned in King James Bible" },
{ 2570, "Number of steps to the top of the CN Tower" },
{ 2525, "ID number of the bus in Speed" },
{ 2500, "Population of Bedrock" },
{ 2343, "Number of episodes of Howdy Doody" },
{ 2240, "Number of pounds in on long ton" },
{ 2224, "Number of passengers and crew on board the titanic" },
{ 2211, "Badge number of Dirty Harry" },
{ 2000, "The length of the course for a mens olympic rowing event" },
{ 1971, "Year Walt Disney World opened in Florida" },
{ 1955, "Year Disneyland in California opened" },
{ 1945, "Year of the end of the 2nd world war" },
{ 1939, "Year of the start of the 2nd world war" },
{ 1912, "Year the titanic sank" },
{ 1901, "Year of the death of Queen Victoria" },
{ 1815, "Height of Toronto's CN Tower in feet" },
{ 1810, "Year of the first recorded womens' golf tournament" },
{ 1799, "The year the rosetta stone was discovered" },
{ 1770, "Year of The Boston Massacre" },
{ 1701, "Year of the War of the Spanish Succession" },
{ 1665, "Number of steps to the top of the Eiffel Tower" },
{ 1641, "The year the thermometer was invented" },
{ 1620, "Inscription on Plymouth Rock" },
{ 1569, "Number of lines spoken by Hamlet" },
{ 1500, "Amount of money given to each player in Monopoly in dollars" },
{ 1453, "the year Constantinople fell to the turks" },
{ 1440, "Number of minutes in one day" },
{ 1368, "Start of the Chinese Ming Dynasty" },
{ 1339, "Weight of one cubic foot of pure platinum in pounds" },
{ 1336, "Number of seats in the New York Stock Exchange" },
{ 1323, "Number of words in the Declaration of Independence" },
{ 1281, "Number of goals scored by Pele" },
{ 1230, "the date mongols invaded europe" },
{ 1220, "Number of shoes found in Imelda Marcos closet" },
{ 1206, "Weight of one cubic foot of pure gold in pounds" },
{ 1189, "Weight of one cubic foot of pure uranium in pounds" },
{ 1144, "Start of the second crusade" },
{ 1093, "Number of patents held by Thomas Edison" },
{ 1066, "the year the viking age definitely ended" },
{ 1046, "Number of people that died on the titanic" },
{ 1037, "Number of pages in the 1st edition gone with the wind" },
{ 1036, "Length of presidential term for JFK in days" },
{ 1000, "Length of the course of womens olympic rowing in metres" },
{ 999, "Telephone Number for the Emergency Services in the UK" },
{ 984, "Height of the eiffel tower in feet" },
{ 969, "oldest age recorded in the bible" },
{ 962, "second oldest recorded age in the bible" },
{ 954, "Length of the all-american soap box derby in feet" },
{ 947, "length of the Enterprise-A in feet" },
{ 921, "Length of each outer wall of the pentagon in feet" },
{ 897, "Number of steps to the top of the washington monument" },
{ 894, "Career goals scored by NHL great wayne gretsky" },
{ 882, "Length in feet of the titanic" },
{ 850, "price of the first model T ford in dollars" },
{ 823, "Number of words in one sentence in the novel les miserables" },
{ 800, "Car capacity of the garage of the sultan of brunei" },
{ 793, "the year the vikings raided lindisfarne" },
{ 792, "number of 3 digit numbers that may be used as area codes" },
{ 777, "The holy number" },
{ 714, "Badge number of Joe Friday" },
{ 708, "weight of one cubic ft of pure lead in lbs" },
{ 666, "Satan's number" },
{ 660, "days of average gestation of an african elephant" },
{ 655, "weight of one cubic ft of pure silver in lbs" },
{ 650, "Typical beats per minute heart rate of a mouse" },
{ 640, "Number of acres in one square mile" },
{ 639, "Number of muscles in the adult human body" },
{ 600, "The weight of a womans javelin in grams" },
{ 580, "Number of characters in the novel war and peace" },
{ 555, "Ficticious phone prefix used in films and TV" },
{ 532, "The total length of the library of congress bookshelves in miles" },
{ 512, "Average number of plain M&M's per pound" },
{ 511, "career number of wins by cy young" },
{ 490, "Number of US currency notes to the pound" },
{ 480, "Standard weight of a US bail of cotton in lbs" },
{ 444, "The length of time 52 hostages were held in Iran in days" },
{ 423, "Number of karats in the star of rhodesia" },
{ 417, "The width of the Enterprise-A in feet" },
{ 403, "Number of stairs to the top of the Statue of Liberty" },
{ 400, "the minimum distance from home plate to centre field fence in NLB" },
{ 375, "Number of voices in the mormon tabernacle choir" },
{ 364, "Total number of gifts given in the 12 days of christmas" },
{ 361, "Number of points on the board in the game 'Go'" },
{ 360, "Number of watchtowers that guarded the ancient city of babylon" },
{ 336, "Number of dimples on an american golf ball" },
{ 325, "Length in days of the reign of Edward VIII" },
{ 324, "number of possible solutions in the game 'cluedo'" },
{ 322, "Number of saturday evening post covers drawn by norman rockwell" },
{ 321, "Area code for cape canaveral" },
{ 313, "Record number of lawsuits by pitcher cy young" },
{ 311, "Number of athletes in the first olympics" },
{ 300, "The perfect game in bowling" },
{ 294, "Number of steps to the top of the leaning tower of pisa" },
{ 293, "Number of combinations of US coins that total a dollar" },
{ 285, "Number of ferengi rules of aquisition" },
{ 284, "Number of restrooms in The Pentagon" },
{ 270, "number of lectoral votes needed to win a presidential election" },
{ 257, "number of times the word Fuck is used in Pulp Fiction" },
{ 255, "highest number possible with one byte" },
{ 254, "number of counties in the state of Texas" },
{ 250, "the cost of a vowel on american wheel of fortune" },
{ 240, "number of bedrooms in Buckingham Palace" },
{ 231, "number of cubic inches in one gallon (rounded off)" },
{ 229, "age of \"Alf\"" },
{ 225, "number of squares on a scrabble board" },
{ 220, "number of different words used in cat in the hat" },
{ 206, "number of bones in the adult human body" },
{ 200, "number of milligrams in one karat" },
{ 195, "number of woody woodpecker cartoons" },
{ 192, "the average number of peanut M&M's per pound" },
{ 190, "number of \"3 stooges\", shorts" },
{ 188, "number of languages robby the robot knows" },
{ 184, "the weight of sputnik-1 in lbs" },
{ 180, "the maximum allowable weight for a mercury astronaught in lbs" },
{ 178, "the average number of seseme seeds on a mcdonalds big mac bun" },
{ 172, "age of lola in the musical 'damn yankees'" },
{ 169, "the weight of one cubic foot of pure aluminium in lbs" },
{ 168, "total number of spots on a standard set of dominoes" },
{ 167, "number of womens single tournaments won by martina navratilova" },
{ 162, "number of regular season MLB games" },
{ 160, "width of NFL field in feet" },
{ 154, "number of sonnets attributed to shakespeare" },
{ 153, "number of john wayne films" },
{ 151, "number of spaces on the board game \"Uncle Wiggily\"" },
{ 150, "seating capacity at the 'round table' at the court of king arthur" },
{ 144, "standard number of tiles in a Mah Jongg set" },
{ 142, "number of stairways at Hogwarts" },
{ 136, "numbers of marches composed by Souse" },
{ 135, "number of chapters in Moby Dick" },
{ 134, "in ounces weight of the America's Cup trophy" },
{ 133, "number of ridges on the edge of a susan b anthony dollar" },
{ 132, "number of islands that make up the state of hawaii" },
{ 125, "number of times duke is sung in \"the duke of earl\"" },
{ 124, "number of munchkins in the wizard of oz" },
{ 121, "Winning point total in cribbage" },
{ 120, "Length in feet of the worlds shortest river" },
{ 119, "number of ridges on a US quarter" },
{ 118, "number of islands upon which Venice is built" },
{ 117, "highest track number at NYC's Grand Central Station" },
{ 116, "length of the hundred years war" },
{ 114, "number of chapters that make up the Koran" },
{ 112, "number of cards used in mille bournes" },
{ 111, "emergency phone number in New Zealand" },
{ 110, "number of Cornets in \"Seventy Six Trombones\"" },
{ 109, "number of men's pro singles tournaments won by jimmy connors" },
{ 108, "number of cards used in the game Uno" },
{ 105, "number of betty boop cartoons" },
{ 102, "number of passengers on the mayflower at plymouth" },
{ 100, "number of letter tiles in scrabble" },
{ 96, "Periodic table number for Curium" },
{ 94, "standard weight of US bag of cement in lbs" },
{ 93, "Flight number of United plane that crashed in PA on 9/11/01" },
{ 91, "number of times Earl Weaver was ejected from a MLB game" },
{ 90, "number of horses on the walt disney world carousel" },
{ 88, "number of keys on a standard piano" },
{ 86, "number of symbols in the Cherokee alphabet" },
{ 83, "number of functions of the cigarette lighter in Our Man Flint" },
{ 82, "number of regular season NHL games" },
{ 80, "number of numbers to select from in casino keno" },
{ 79, "number of episodes in original star trek" },
{ 78, "farenheit melting point of cocoa butter" },
{ 76, "number of letters in the Thai alphabet" },
{ 73, "number of elevators in the empire state building" },
{ 71, "number of known moons in the solar system" },
{ 70, "length of a field hockey game in minutes" },
{ 68, "percentage of air in hostess twinkies" },
{ 66, "number of books in the christian protestant bible" },
{ 65, "shoe size of Snuffleupagus on seasme street" },
{ 64, "number of academy award nominations for Walt Disney" },
{ 63, "length of wire to make a slinky in feet" },
{ 62, "salary of Ralph Kramden on the Honeymooners in dollars" },
{ 61, "number of NHL records by Wayne Gretzky" },
{ 60, "number of spaces on a 'Sorry' board" },
{ 58, "number of facets on a round brillant cut diamond" },
{ 57, "number of men killed by \"Rambo\"" },
{ 56, "number of signers of the declaration of independence" },
{ 54, "number of times Richard Nixon was on the cover of Time" },
{ 53, "number on the side of 'herbie the love bug'" },
{ 52, "highest postition ever reached in ratings for the original Star Trek" },
{ 51, "Number of founding nations of the UN" },
{ 50, "Number of ways to leave your lover" },
{ 49, "Number of victories by boxing champ rocky" },
{ 48, "number of cards in a pinocle deck" },
{ 47, "Number of strings on a standard harp" },
{ 46, "Number of chromasomes in a normal human cell" },
{ 45, "Height of the letters in the hollywood hills sign in feet" },
{ 44, "Rob Niedermayer's number (hockey player)" },
{ 43, "Number of muscles needed to frown" },
{ 42, "Number of gallons of oil in one barrel" },
{ 41, "Number of signers of the mayflower compact" },
{ 40, "Number of spaces around a monopoly board" },
{ 39, "number of signers of the US constitution" },
{ 38, "numbers on a roulette wheel" },
{ 37, "number of plays by shakespere" },
{ 36, "Number of footballs made available in an NFL game" },
{ 35, "Minimum age for a US president" },
{ 34, "length of reigh of pope john paul I, in days" },
{ 33, "number of letters in the russian alphabet" },
{ 32, "number of bathrooms in the whitehouse" },
{ 31, "number of states in mexico" },
{ 30, "minimum age for a member of US Senate" },
{ 29, "Days in February in a Leap Year" },
{ 28, "number of purchasable spaces in Monopoly" },
{ 27, "number of wives of Mormon leader Brigham Young" },
{ 26, "number of innings in the longest MLB game" },
{ 25, "minimum age for a member of the house of representatives" },
{ 24, "number of letters in the greek alphabet" },
{ 23, "number of different fruit flavors in dr pepper" },
{ 22, "number of lettes in the Hebrew alphabet" },
{ 21, "number of letters in the Italian alphabet" },
{ 20, "number of possible first moves in chess" },
{ 19, "typical number of hours per day a sloth sleeps" },
{ 18, "number of precooked white castle hamburgers to the pound" },
{ 17, "number of muscles needed to smile" },
{ 16, "number of initial contestants on Survivor" },
{ 15, "number of books in the book of mormon" },
{ 14, "number of pounds in one stone" },
{ 13, "number of layers in a mcdonalds big mac" },
{ 12, "number of letters in the hawaiian alphabet" },
{ 11, "number of players on a cricket team" },
{ 10, "number of marbles per player in chinese checkers" },
{ 9, "highest score in the casino game baccarat" },
{ 8, "number of storeys in the leaning tower of pisa" },
{ 7, "number of different fruits in Hawaiian punch" },
{ 6, "number of locks in the panama canal" },
{ 5, "number of standard foot positions in classical ballet" },
{ 4, "number of toes on a cuckoo" },
{ 3, "minimum people needed for a riot" },
{ 2, "Number of teeth Disney character Goofy has" },
{ 1, "One more than the edges on a sphere" }
};
